version: '3'
services:
  vault:
    build: ./vault/
    restart: always
    ports:
      - "8200:8200"
    volumes:
      - vault_data:/vault/config/
      - vault_data:/vault/certs/
      - vault_data:/vault/data/
    networks:
      - back-tier

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
    ports:
      - "8100:8100"

  api:
    depends_on:
      - vault
      - db
    build: ./api/
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - ./api/.env
    networks:
      - back-tier
networks:
  back-tier: {}

volumes:
  vault_data: {}
